---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-watcher
  name: kube-watcher
  namespace: kube-watcher
spec:
  selector:
    matchLabels:
      app: kube-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-watcher
    spec:
      containers:
        - image: flytux/kube-watcher:0.1.0-minimum
          imagePullPolicy: Always
          name: kube-watcher
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
            - rancher.do
          ip: 64.227.23.169
        - hostnames:
            - prometheus.do
          ip: 64.227.23.169
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-watcher
  name: kube-watcher
  namespace: kube-watcher
spec:
  ports:
    - name: http-kube-watcher
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
      app: kube-watcher
  sessionAffinity: None
  type: NodePort