spring.datasource.data: classpath:sql/import.sql
spring.datasource.schema: classpath:sql/schema.sql

spring.datasource.initialization-mode: always
spring.datasource.driver-class-name: org.h2.Driver
spring.datasource.url: "jdbc:h2:mem:kubeworksdb;AUTO_SERVER=FALSE;IFEXISTS=false;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL;"
spring.datasource.username: sa
spring.datasource.password:

spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.hbm2ddl.import_files: ""
