{
 "title": "JVM dashboard - overview",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [
  "JVM",
  "beta-version"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": "label_values(jvm_info{job=\"jvm\"},application)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_info{job=\"jvm\", application=\"$application\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Available JVM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_info{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "avg(irate(os_process_cpu_load{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Heap Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg((jvm_memory_bytes_used{area=\"heap\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"} / jvm_memory_bytes_max{area=\"heap\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"} >= 0) * 100)"
    }
   ]
  },
  {
   "title": "Active Thread",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Avg. GC Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_collection_seconds_sum{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{application=~\"^$application$\", instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(process_start_time_seconds{application=~\"^$application$\", instance=~\"^$instance$\"})*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",application=~\"^$application$\", instance=~\"^$instance$\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\", application=~\"^$application$\", instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_info{application=~\"^$application$\", instance=~\"^$instance$\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "os_system_cpu_load{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "System  [{{application}} - {{instance}}]"
    },
    {
     "expr": "os_process_cpu_load{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "JVM [{{application}} - {{instance}}]"
    }
   ]
  },
  {
   "title": "Memory area [heap]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"jvm\",application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}} - {{instance}}]"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"jvm\",application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}} - {{instance}}]"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"} / jvm_memory_bytes_max{area=\"$memarea\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"} >= 0",
     "legendFormat": "Usage(%) [{{application}} - {{instance}}]"
    }
   ]
  },
  {
   "title": "Memory area [noheap]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=\"jvm\",application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}} - {{instance}}]"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"nonheap\",job=\"jvm\",application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}} - {{instance}}]"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"} / jvm_memory_bytes_max{area=\"$memarea\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"} >= 0",
     "legendFormat": "Usage(%) [{{application}} - {{instance}}]"
    }
   ]
  },
  {
   "title": "Memory pool [Code Cache]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Code Cache\", job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Code Cache\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Code Cache\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory pool [Compressed Class Space]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\", job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory pool [Eden Space]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Eden Space\", job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Eden Space\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Eden Space\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory pool [Metaspace]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\", job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory pool [Survivor Space]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Survivor Space\", job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Survivor Space\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Survivor Space\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory pool [Tenured Gen]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Tenured Gen\", job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Max [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Tenured Gen\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Used [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Tenured Gen\",job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"jvm\", application=~\"^$application$\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}} [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"jvm\", application=~\"^$application$\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}} [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Current [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_threads_daemon{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Daemon [{{application}}-{{instance}}]"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Deadlocked [{{application}}-{{instance}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_total_physical_memory_bytes{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Total physical [{{application}}-{{instance}}]"
    },
    {
     "expr": "os_committed_virtual_memory_bytes{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Committed virtual [{{application}}-{{instance}}]"
    },
    {
     "expr": "os_free_physical_memory_bytes{job=\"jvm\", application=~\"^$application$\", instance=~\"^$instance$\"}",
     "legendFormat": "Free physical [{{application}}-{{instance}}]"
    }
   ]
  }
 ]
}