{
 "title": "Oracle DB",
 "description": "oracledb dashboard",
 "tags": [ "Oracle" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "oracledb_uptime" },
   {
    "name": "dbinstance",
    "label": "Instance",
    "query": "oracledb_uptime{database=\"$database\"}"
   },
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Oracel overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime $dbinstance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "dbinstance",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(oracledb_uptime{dbinstance=~'$dbinstance'}) without (job)"
    }
   ]
  },
  {
   "title": "oracledb status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{status=\"ACTIVE\",type=\"USER\"}"
    }
   ]
  },
  {
   "title": "user commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "execute count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Oracle Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions $dbinstance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "repeat": "dbinstance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_session{dbinstance=~\"$dbinstance\"}) without (job)",
       "legendFormat": "{{state}} {{type}}"
      }
     ]
    },
    {
     "title": "User Commits / Rollbacks $dbinstance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "dbinstance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(oracledb_sysstat{dbinstance=~'$dbinstance',type=~'.*commit.*|.*rollback.*'}[10m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio $dbinstance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "dbinstance",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_cachehitratio{dbinstance=~\"$dbinstance\",type!='cursor_cache_hit_ratio'}) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Executions / Parses $dbinstance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "repeat": "dbinstance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(oracledb_sysstat{dbinstance=~'$dbinstance',type=~'.*count.*'}[10m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Cursor Cache Hit Ratio $dbinstance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "repeat": "dbinstance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_cachehitratio{dbinstance=~\"$dbinstance\",type='cursor_cache_hit_ratio'}) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "wait time concurrency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "wait time commit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "oracledb_wait_time_commit{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "wait time system io",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "oracledb_wait_time_system_io{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "wait time user io",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t"
      }
     ]
    },
    {
     "title": "wait time application",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "oracledb_wait_time_application{instance=\"$host\"}\t"
      }
     ]
    },
    {
     "title": "wait time network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "oracledb_wait_time_network{instance=\"$host\"}\t"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle FRA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "FRA Used",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
     "format": "percent",
     "valueName": "max",
     "targets": [
      {
       "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_used\"})"
      }
     ]
    },
    {
     "title": "FRA Reclaimable",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_reclaimable\"})"
      }
     ]
    },
    {
     "title": "Redolog Switches in Last 5 min",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(oracledb_redo{database='$database'})"
      }
     ]
    },
    {
     "title": "FRA Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_used\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_reclaimable\"})",
       "legendFormat": "Reclaimable"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle transfer RAC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Events $dbinstance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_waitclass{dbinstance=~'$dbinstance'}) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Interconnect  Block Transfer $dbinstance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(rate(oracledb_interconnect{dbinstance=~'$dbinstance'}[5m])) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Physical Throughput $dbinstance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_sysmetric{dbinstance=~'$dbinstance',type=~'.*bytes.*'}) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Physical IOPs $dbinstance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_sysmetric{dbinstance=~'$dbinstance',type=~'.*requests.*'}) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Events $database",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(oracledb_waitclass{database='$database'}) without (instance,dbinstance,job)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Interconnect Block Transfer $database",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(sum(rate(oracledb_interconnect{database='$database'}[5m])) without (instance)) without (job)",
       "legendFormat": "{{dbinstance}}:{{type}}"
      }
     ]
    },
    {
     "title": "Physical Throughput $database",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(sum(oracledb_sysmetric{database='$database',type=~'.*bytes.*'}) without (instance,dbinstance)) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Physical IOPs $database",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "avg(sum(oracledb_sysmetric{database='$database',type=~'.*requests.*'}) without (instance,dbinstance)) without (job)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle tablespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table space status",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "1-(oracledb_tablespace_free{instance=\"$host\"}/oracledb_tablespace_max_bytes{instance=\"$host\"})"
      },
      {
       "expr": "oracledb_tablespace_free{instance=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oracle errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Valid Errors",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "oracledb_error{dbinstance=~'$dbinstance',ignore=\"0\"}"
      }
     ]
    },
    {
     "title": "Ignored Errors",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "oracledb_error{dbinstance=~'$dbinstance',ignore=\"1\"}"
      }
     ]
    },
    {
     "title": "Altertlog last modified $dbinstance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - avg(oracledb_error_unix_seconds{database!='+ASM',dbinstance=~'$dbinstance'}) without (job)",
       "legendFormat": "{{dbinstance}}"
      }
     ]
    }
   ]
  }
 ]
}