{
 "title": "System Processes Metrics",
 "description": "Show Linux Process information as captured by \n https://github.com/ncabatoff/process-exporter  designed for PMM",
 "tags": [ "Insight" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(namedprocess_namegroup_num_procs, instance)"
   },
   {
    "name": "processes",
    "label": "Processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\"},groupname)"
   }
  ]
 },
 "panels": [
  { "title": "Process CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top processes by Total CPU cores used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) \n+\nrate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]))\nor \n(irate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])\n+\nirate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by System CPU cores used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,\nrate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])\nor \n(\nirate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Top processes by Used  memory",
   "type": "graph",
   "description": "Memory Used by Processes, counted as Resident Memory + Space used in Swap Space",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\r\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[$interval])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[$interval]))\r\nor\r\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[5m])+ ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[5m]))\r\n))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Resident Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[$interval]) \nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[5m])\n))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Virtual memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$host\"}[$interval])\nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$host\"}[5m])))\n",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Swapped Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[$interval])\nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[5m])))\n",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Disk IO Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Top processes by Bytes Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,(rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or irate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Bytes Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,(rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or irate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process and Thread Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top processes by number of  processes instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,(max_over_time(namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) \nor max_over_time(namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,(max_over_time(namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Context Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Top Processes by Voluntary Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top Processes by  Non-Voluntary Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Top processes by Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,(max_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by File Descriptor Usage Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_worst_fd_ratio{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_worst_fd_ratio{groupname=~\"$processes\",instance=~\"$host\"}[5m])\n))*100",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Page Faults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Top processes by Major Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Minor Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Top running processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Running\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Running\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top of processes waiting on IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Kernel Waits (WCHAN)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Kernel waits for $processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=~\"$host\", groupname=~\"$processes\"}[$interval])) by (wchan) )",
     "legendFormat": "{{wchan}}"
    }
   ]
  },
  {
   "title": "Kernel wait Details for $processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=~\"$host\", groupname=~\"$processes\"}[$interval])) by (wchan,groupname) )",
     "legendFormat": "{{groupname}} : {{wchan}}"
    }
   ]
  },
  { "title": "Process Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Processes by uptime",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "time()-(namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$host\"}>0)"
    }
   ]
  }
 ]
}