#Kubewatcher 추가된내용 - 20210310
#...
- job_name: external-node-metrics
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: [10.253.216.11:9100, 10.253.216.23:9100]
      labels:
        zone: 'external'
- job_name: process-metrics
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: [10.253.216.11:9256, 10.253.216.23:9256]
      labels:
        zone: 'external'
    - targets: [10.253.208.150:9256, 10.253.208.151:9256, 10.253.208.152:9256, 10.253.208.153:9256, 10.253.208.154:9256, 10.253.208.155:9256, 10.253.208.156:9256, 10.253.208.157:9256]
      labels:
        zone: 'cluster'
- job_name: oracle-metrics
  scrape_interval: 39s
  scrape_timeout: 38s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: [10.253.216.11:9162, 10.253.216.23:9162]
      labels:
        zone: 'external'
        scrape_type: 'normal'
- job_name: 'jmx-metrics'
  scrape_interval: 10s
  kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - dev-core-ns
          - dev-cust-ns
          - dev-pica-ns
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    action: keep
    regex: 9210
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: namespace
    regex: (.+)
  - source_labels: [__meta_kubernetes_pod_container_name]
    action: replace
    target_label: application
    regex: (.+)
